### ISSUE TITLE
Level One Background

### ISSUE THREAD

**Issue by brittanyellich** [knot-games/cloud-tycoon#37]
As a player, I need a background image that conveys that I'm in a garage that has been turned into a server room.

- [x] Background image asset is found or created
- [x] Background image asset is added to LoadAssets() on the boot level
- [x] Background image asset is added to level one

Epic: https://github.com/knot-games/cloud-tycoon/issues/24

**Comment by robherley** [comment]
first stab: 

![mock](https://user-images.githubusercontent.com/16991201/200154492-332eb1a4-9288-46a0-925e-7b44d23d026a.png)

**Comment by robherley** [comment]
all done
